### ISSUE TITLE
Pseudotime differences

### ISSUE THREAD

**Issue by MarieCoutelier** [theislab/cellrank#1107]
Hi, 

I have a generic question about the use of Cellrank -my apologies if it is super basic, I'm not super at ease with all the subtleties of the different versions. 

In the previous version, Cellrank allowed to compute the equivalent of a pseudotime, which was different than both the velocities pseudotime and the Palantir pseudotime, if I'm correct (I remember three plots of pseudotime in the tutorial, which I can't find anymore). 
In this new version, the only pseudotime I see is the Palantir one, and the gene trends plots are made along this pseudotime. 

Could you maybe enlighten me a bit about the differences between these old versions of pseudotimes, why they are not to be found here, and if the best way to study, let's say, the expression of a gene along a differentiation branch hence would indeed be to 
- compute palantir pseudotime
- isolate the branch of interest with cellrank
- plot the gene expression along that branch? (based on the GAM, then?)

Thanks and sorry again for the triviality of my question!

Marie

**Comment by Marius1311** [comment]
Hi @MarieCoutelier, sorry if this seems confusing, let me try to explain:
- I think the "old" pseudotime that you refer to was the CytoTRACE pseudotime, that's just 1-CytoTRACE score, and we show how to compute this here: https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/kernels/400_cytotrace.html. We use this pseudotime in the `CytoTRACEKernel` to direct kNN-graph edges to point into the direction of increasing maturity.
- In addition, in the `PseudotimeKernel`, you can use any pseudotime you like to do something very similar - direct kNN graph edges to point from less mature towards more mature cells. In the tutorial (https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/kernels/300_pseudotime.html), we show this for the Palantir pseudotime, but you should use whatever Pseudotime works best for your dataset. 
- The velocity pseudotime is computed in scVelo and has no direct connection to CellRank - you can use that in the Pseudotime kernel if you wish, just like any other pseudotime. 

Now, if you want to visualize gene expression trends along a pseudotime, you can essentially follow the steps you outlined above. I suppose that by "isolating the branch interest", you mean computing fate probabilities, which would be my preferred solution. However, note that again, you can use *any* pseudotime you like here, not just the Palantir pseudotime. If Palantir works well for your data, then that's great and you should go with it. If you have another favourite pseudotime algorithm, and you have already computed a pseudotime with this algorithm, which confirms with some notion of ground truth on your dataset, then just use that. We intentionally made CellRank 2 very modular and did not tie it to any particular pseudotime algorithm, so that you can use whatever works on your data. Hope this helps!

**Comment by Marius1311** [comment]
Closing this, feel free to reopen if your original question has not been sufficiently addressed yet.
