### ISSUE TITLE
Setting of vk.plot_projection()

### ISSUE THREAD

**Issue by LalicJ** [theislab/cellrank#1118]
...
Thank you for developing such a nice tool for unified cell fate inference. I try to follow your tutorial as shown here: https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/kernels/200_rna_velocity.html for my own data. 
But when I run `vk.plot_projection()`, I got a figure without annotations or color. I don't know what went wrong. I wonder are there any parameters that can change the color of the graph? Any help would be greatly appreciated.
![image](https://github.com/theislab/cellrank/assets/120431995/2f61853f-1903-4fab-8c2d-30af68ce5150)

**Comment by michalk8** [comment]
Hi @LalicJ , `plot_projection` takes the same arguments as [scvelo.pl.velocity_embedding_stream](https://scvelo.readthedocs.io/en/latest/scvelo.pl.velocity_embedding_stream.html#scvelo.pl.velocity_embedding_stream) or [scvelo.pl.velocity_embedding_grid](https://scvelo.readthedocs.io/en/latest/scvelo.pl.velocity_embedding_grid.html#scvelo.pl.velocity_embedding_grid), depending on the `stream` argument. You should be able to pass `color=<some annotation in obs>` to have some colors (I assume it doesn't work by default in your case because `scvelo` tries to automatically find some annotations sometimes).

**Comment by LalicJ** [comment]
Thanks for you reply! I can run it with color now.
