### ISSUE TITLE
Available GPU support in CellRank 2?

### ISSUE THREAD

**Issue by zvittorio** [theislab/cellrank#1151]
Dear CellRank team, 

first of all thanks for this amazing tool! 
I am trying to install CellRank on a high performance computing system, in particular on the GPU clusters so that CellRank can work optimally. However, I see no dependencies that allow GPU computing... 
From some of the issues in the repo I would assume it's JAX, but it doesn't seem to be a dependency, not even optional. 
So my question is, what kind of GPU support is available in Cellrank 2.x, and how can it be used?

Thanks for the help

Vittorio

**Comment by Marius1311** [comment]
Hi @zvittorio, CellRank 2 currently does not make use of GPU hardware acceleration for any of its core computations. Instead, it uses very high performance libraries like SLEPc and PETSc and optimally exploit sparsity in our transition matrices. This enables us to process even very large datasets (>1M cells) efficiently on CPU. Are you currently facing any performance bottleneck in CellRank 2? 

There is one place where CellRank 2 could in principle use GPU acceleration - the forward pass in the VelocityKernel is implemented using JAX. However, the motivation for that was to enable automatic differentiation to approximate the uncertainty in computed transitions, rather than hardware acceleration. 

Also, note that moscot, which CellRank 2 interfaces with for Time series, lineage-tracing and spatio-temporal datasets, is implemented in JAX and makes use of GPUs throughout all major computations.

**Comment by michalk8** [comment]
Unfortunately, there are no plans to include any GPU support...
The biggest gains in terms of using GPUs for computation would be in [pyGPCCA](https://github.com/msmdev/pygpcca) (for metastable state computation, PETSc/SLEPC seems to support, e.g., CUDA as a backend) when computing the absorbing state of the Markov chain.

**Comment by zvittorio** [comment]
Dear @Marius1311 @michalk8 
I must have misunderstood some other issues where GPU was mentioned, but apparently not actively used for cellrank calculations (e.g., #757 ). 
Thank you again for the clarification!
