### ISSUE TITLE
PETSc installation error

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#149]
Joe had this error when trying to run `./configure`:

![image](https://user-images.githubusercontent.com/24494650/83499459-b4f5c000-a4bd-11ea-8344-d85ec4036aa6.png)

@michalk8 , any idea how to solve this?

**Comment by Marius1311** [comment]
I'm collecting all of these installation errors so we can have a "troubleshooting" section in the docs.

**Comment by michalk8** [comment]
Can I see the `configure.log`?

**Comment by michalk8** [comment]
I can try spinning up some docker containers based on Arch/Ubuntu/etc. and see what the common issues are there.

**Comment by Marius1311** [comment]
that would be fantastic and probably very helpful for many people.

**Comment by jmchan88** [comment]
So sorry about the delay! I'm attaching the configure.log now. 

Thank you so much for helping with this!

[configure.log](https://github.com/theislab/cellrank/files/4730518/configure.log)

**Comment by michalk8** [comment]
Seems like a linker problem, here's relevant thread I found on anaconda:
https://github.com/ContinuumIO/anaconda-issues/issues/5191
Symlinking to a newer version seems to have worked, base on this:
https://github.com/ContinuumIO/anaconda-issues/issues/5191#issuecomment-368243432

**Comment by Marius1311** [comment]
@jmchan88 , would be great if you could give this a go once you find the time.

**Comment by jmchan88** [comment]
Absolutely, thank you so much, I really appreciate it! I will try to get this working and update you guys as soon as I can.

**Comment by Marius1311** [comment]
sounds good!

**Comment by jmchan88** [comment]
Apologies for taking so long to get around to this, but I cleared my schedule so I can focus on this now! I took a look though and I don't it's a symlink issue, at least as detailed in that thread on anaconda. For me, the symlink already set up is:

/home/chanj3/anaconda3/lib/libstdc++.so.6 -> libstdc++.so.6.0.25 

This should be work, shouldn't it?

**Comment by michalk8** [comment]
@jmchan88 
Yes, that should be fine. I've noticed you have old version of GCC:
```
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
```
Can you try upgrading it? Based on this [SO thread](https://stackoverflow.com/questions/29230777/program-linking-fails-when-using-custom-built-gcc), the issue is one of these missing symbols, which were added in later version of GCC:

```
__cxa_throw_bad_array_new_length was added in GCC 4.9. That's what the @CXXABI_1.3.8 
version suffix means. You can look up those version codes here: https://gcc.gnu.org/onlinedocs
/libstdc++/manual/abi.html
```
Which is exactly what your log mentions:
`/home/chanj3/anaconda3/lib/libicuuc.so.58: undefined reference to __cxa_throw_bad_array_new_length@CXXABI_1.3.8'`

As for me, I had no troubles with this version of GCC: `gcc (Debian 9.3.0-13) 9.3.0`.

**Comment by jmchan88** [comment]
Ah ok, thanks for the lead! I'll try to follow it up ... i'm trying to install it on the institutional computer cluster where I don't have root access, so it might be a little cumbersome!

**Comment by Marius1311** [comment]
Would be fantastic to find out whether Mike's suggestion solves the issue for further installations. Thanks for your help @jmchan88 !

**Comment by jmchan88** [comment]
OK, I tried installing with an updated gcc version 9.3.0. I'm not sure but I think it's a similar error, though maybe the stdout was different in the image below? I'm attaching the configure.log as well. Hopefully getting closer!

[configure.log](https://github.com/theislab/cellrank/files/4823039/configure.log)

![image](https://user-images.githubusercontent.com/12499408/85494912-91e39b00-b5a7-11ea-808b-861152fedb9f.png)

**Comment by jmchan88** [comment]
I believe I have also already installed MPICH successfully too!

**Comment by michalk8** [comment]
@jmchan88 
I think the problem is still the same. During the installation, for some reasons, it uses `GCC 4.8.5` (line 310) and there, the symbols are not defined. Inside the log (line 310), it detects the following installation:
```
Checking for program /home/chanj3/mpich-install/bin/gcc...not found
Checking for program /home/chanj3/bedtools2/bin/gcc...not found
Checking for program /admin/lsflilac/lsf/gcc...not found
Checking for program /home/chanj3/.local/bin/gcc...not found
Checking for program /home/chanj3/anaconda3/bin/gcc...not found
Checking for program /home/chanj3/.local/bin/gcc...not found
Checking for program gcc...not found
Checking for program /home/chanj3/bin/gcc...not found
Checking for program /usr/bin/gcc...found
              Defined make macro "CPP" to "gcc -E
```
And e.g. on (line 8669):
```
Executing: /lila/home/chanj3/petsc/arch-linux-c-debug/bin/mpicc --version
stdout:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc
```

Same when searching for `g++` or `gfortran`, which is expected. Furthermore, there are issues that point to the version problem, like:
```
g++ error: unrecognized command line option ‘-std=gnu++14`
```
which is again due to the wrong version (based on [this](https://stackoverflow.com/questions/39871129/c-error-unrecognized-command-line-option-std-gnu14), `4.9.*` or greater is required).
Could you please check where is your newest GCC installed and make sure it's used for the compilation and not hte old one? I think the path to it must be after `/usr/bin` in `$PATH`, so that's why it's being used.

**Comment by Marius1311** [comment]
@jmchan88 , has this been solved?

**Comment by jmchan88** [comment]
Ah unfortunately not ... will try to get back to this as soon as I can!

**Comment by Marius1311** [comment]
we have made quite a lot of changed to our installation routine - I think the easiest solution would be for you to entirely remove cellrank, open a new conda environment and then install cellrank with PETSc and SLEPSc dependencies via
```
conda install -c conda-forge -c bioconda cellrank-krylov
```

**Comment by jmchan88** [comment]
Ah ok that sounds great! I'll give that a go and let you guys know! Thanks
Marius!

**Comment by Marius1311** [comment]
Assuming that this has been solved, I'm closing. If the error persists, feel free to reopen @jmchan88
