### ISSUE TITLE
Automate updating of tutorial notebooks

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#196]
I'm unsure whether our tutorial notebooks are updated automatically in the docs. I changed the tutorials and merged them into master in `cellrank_notebooks`. However, this did not have any effect on the notebooks in the docs yet. Do you think this just takes some time?

**Comment by michalk8** [comment]
No, the docs are created when updating the main repo now. I will look on how to trigger docs build based on the changes in the notebook repo - maybe the GH workflows could work there.

**Comment by Marius1311** [comment]
cool, thanks.

**Comment by VolkerBergen** [comment]
I don't think you can automate triggering the main repo build - but it's just a one-button click at readthedocs.org to trigger it manually once you have updated the notebooks.

**Comment by michalk8** [comment]
I think it can be done, based on the following stuff:
- [x] enable generic API incoming webhook: https://readthedocs.org/dashboard/cellrank/integrations/
- [ ] add a RTFD and ACCESS secret for the API token [here](https://github.com/theislab/cellrank/settings) (here's the how-to [resource](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)), @Marius1311 I don't see the option, because I don't think I have the permission (maybe you have, but I think only `theislab` user does)
- [ ] recreate a simplified version of [this](https://blog.marcnuri.com/triggering-github-actions-across-different-repositories/) - i.e. just ping, no pong, use the token secrets from above, using the generic [API](https://docs.readthedocs.io/en/stable/webhooks.html#using-the-generic-api-integration)

Somewhat related is this [action](https://github.com/marketplace/actions/sphinx-build) - just builds the docs, but RTFD can already do that on PR, so I don't think it's currently necessary.

**Comment by Marius1311** [comment]
Thanks Mike, let's set this up together in our Wednesday call

**Comment by michalk8** [comment]
@Marius1311 I've tested this, should be working now. There still remains to do some error checking if the request has been sent (from the notebooks_repo and as well from this repo to RTD - I will create a new PR for that [still need to read on the GH actions on how to do that properly.])

**Comment by Marius1311** [comment]
Thanks a lot Mike, very well done, as always.
