### ISSUE TITLE
Include cellrank in the scanpy ecosystem

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#241]
Including links to cellrank, interactive-plotting and scachepy in the scanpy docs under `ecosystem` would be easy and effective advertisement I believe. The corresponding scanpy issue is here: https://github.com/theislab/scanpy/issues/1282

**Comment by michalk8** [comment]
Do you really want to include `scachepy` and `interactive_plotting`? I'd foregone at least one of them (namely ipl) or both,
since I don't think any of them are stable. I have plans to improve `scachepy` (I'd welcome if you have any requests or new conceptual ideas), since it will be faster than changing `ipl` (summer project I guess). There I need to think about its philosophy/intended usage.
If you want to include both of them, I will first package them and add at least a few tests.

**Comment by Marius1311** [comment]
okay, let's just make a PR to include cellrank then for now and the others will follow once you are happy with them.

**Comment by Marius1311** [comment]
Thanks for opening the PR!
