### ISSUE TITLE
Sklearn substitute of GamMGCVModel

### ISSUE THREAD

**Issue by cdedonno** [theislab/cellrank#283]
Hi guys, in the docs you mention the possibility to use sklearn models to compute smooth gene trends instead of using R's mgcv. Getting R to work smoothly with Python is quite a pain and it would be useful to know what you think is the most appropriate sklearn model. A code snippet to show how to integrate it in cellrank would also be very useful. I saw there is a sklearn model wrapper in your code but it is not clear how it works and it is not explained in the docs.

**Comment by Marius1311** [comment]
Thanks for bringing this up @cdedonno ! I think @michalk8 might know more here, he is the expert for the gene expression models in cellrank.

**Comment by michalk8** [comment]
@cdedonno previously, we've used https://pygam.readthedocs.io/en/latest/ (should still worked, wrapped as `SKLearnModel`).
Nonetheless, I will update the docs with some code examples and make sure to throw an error if the underlying model doesn't support weights. I will also add 1 sklearn model which should work out of the box.
@Marius1311 maybe we could include PyGAM, since there are problem with rpy2, or some GLM implementation.

**Comment by Marius1311** [comment]
Hi Mike, yes, I think including one python based model which works into our tutorials would be nice as many people have difficulties with rpy2.
