### ISSUE TITLE
Saving final states from estimator to adata

### ISSUE THREAD

**Issue by timlai4** [theislab/cellrank#297]
I am following the cellrank advanced tutorial for my own scRNA-seq dataset. I have successfully completed the estimator section, including getting similar and expected figures to the ones in the tutorial. I then call `g.set_main_states()` which also runs without any visible errors. From this, I am expecting new columns to be added to my adata object corresponding to the final states computed. However, printing out my columns in my adata object via `print(adata.var.columns)` shows no such columns. In fact, doing a comparison of before and after running the set_main_states shows no change in my adata object. 

I attempted to recreate the situation, running essentially the same commands, with the pancreas dataset including in the vignette. Doing so, I see that the adata object in this case does change as expected. Therefore, I expect this is not an issue with the code, but perhaps with either my dataset or something that I'm overlooking. Because there are no explicit error messages, I am unsure how best to troubleshoot this.

My question is, in such a situation, where are some likely places I might have failed, given that I tried my best to follow the vignette verbatim?

Thank you in advance.

**Comment by michalk8** [comment]
Hi @timlai4 ,
`set_main_states` write to `adata.obs`, not `adata.var`. In case they're missing there, something went wrong indeed. You can also bump the verbosity level to hint `cr.settings.verbosity = 3` - in most cases, it say where it writes.
Fair warning: the tutorial is using `CellRank` as it is on the master, not on `PyPI` or `conda`. I will be pushing new release in the next 2 days tops and after that, everything will be in order.
Let me know if this helps.

**Comment by timlai4** [comment]
Dear @michalk8 , 
Thank you for your prompt reply. I realized that this is indeed the case, and that actually, I meant to describe a different issue. Namely, after this step in the tutorial, we'd like to compute the lineage drivers, and this is supposed to save to `adata.var`, which works for the pancreas dataset, but not my own experiment. Can you advise again on how I might troubleshoot the `g.compute_lineage_drivers()` ?

**Comment by michalk8** [comment]
`compute_lineage_drivers` has parameter `use_raw=True`, which when set, accesses `adata.raw` (if present).
Based on the code you've posted, `WARNING: No raw attribute set. Using `.X` instead`, so it should be in `adata`, and it is, as: `to Ngn3 low EP corr`, `to Alpha corr` and `to Beta corr` (`to` is the direction and `corr` stand for correlation, because that's how we've defined the drivers (still WIP).
Nevertheless, I will update the docs to better reflect how are the names stored.

**Comment by timlai4** [comment]
Apologies for the confusion, the above was for the successful run using the pancreas dataset as in the tutorial. For my experiment, 

```{python}
>>> print(adata.var.columns)
Index(['features', 'ambiguous_features', 'spliced_features',
       'unspliced_features', 'gene_count_corr', 'means', 'dispersions',
       'dispersions_norm', 'highly_variable', 'velocity_gamma', 'velocity_r2',
       'velocity_genes'],
      dtype='object')
>>> g.compute_lineage_drivers()
WARNING: No variation found in `15884` genes. Setting correlation for these to `NaN`
>>> print(adata.var.columns)
Index(['features', 'ambiguous_features', 'spliced_features',
       'unspliced_features', 'gene_count_corr', 'means', 'dispersions',
       'dispersions_norm', 'highly_variable', 'velocity_gamma', 'velocity_r2',
       'velocity_genes'],
      dtype='object')
```

It appears I'm experiencing some issues with missing / zero variation in my genes?

**Comment by michalk8** [comment]
I know why this happens - there's only 1 lineage (`'Alpha'`), that has prob. 1 for all cells. In the correlation computation, we divide by the standard deviation, which is 0.
The question is, why is it all 1s? If there's only 1 lineage, we compute the stationary distribution, which should just sum to 1 (we normalize it so that max element is 1, because of some `scvelo`'s functionalities), that's all. Currently, I have no idea why this happens, maybe there's some issue with the computation of stationary distribution. Can you please check
`g.eigendecomposition["stationary_dist"]?

**Comment by timlai4** [comment]
First, here's the stationary distribution information you requested.
```{python}
>>> print(g.eigendecomposition["stationary_dist"])
[0.00048986 0.00052568 0.00161741 ... 0.00047527 0.00040422 0.0002001 ]
```
Not sure if just five entries is enough to be helpful here, I'll work on finding a way to get it to display more and edit that in later. 

As for the issue, are you suggesting the fact there's only 1 lineage (final state in this case) the issue? I double checked with another sample which had two lineages and I'm seeing similar problems there too, where no columns are being added. Interestingly though, the step `g.compute_lineage_drivers()` does not yield any warnings like the one above. However, in earlier steps in the workflow, I did see the warning: 
> WARNING: No variation found in `12255` genes. Setting correlation for these to `NaN`

A quick attempt to also display the stationary distribution information here ran into some problems
```
    print(g.eigendecomposition["stationary_dist"])
KeyError: 'stationary_dist'
```
I'll try to figure out what went wrong and edit this in later too.

**Comment by michalk8** [comment]
That's strange. There seeems to be some update to lineage object somewhere along the pipeline. As for you seeing the problem with more than 1 lineage, I will check for robustness of the implementation. Is 12255 genes the total number of genes or just a subset? If you could check out after which operation the Lineage object somehow changes (e.g. in the case of 1 lineage), that would be really helpful.

**Comment by michalk8** [comment]
@timlai4 I've finally pushed a new version, it's on PyPI (it will take a few days since it's on Bioconda. It would be great if you could upgrade CellRank and see if the problem persists (I'm afraid it still might). Please beware, there has been some API change, namely function renaming.

**Comment by timlai4** [comment]
@michalk8 I will try to get the new version on my machine and see what that changes. 

> Is 12255 genes the total number of genes or just a subset?
Apologies, I'm more comfortable with Seurat than scanpy. To check this, I thought to do
```{python}
>>> print(adata)
AnnData object with n_obs × n_vars = 7852 × 3000
```
which seems to suggest I have 7852 genes (or 3000 I always forget). However, inspecting with 
```{python}
>>> print(adata.raw.var)
           _index  to Beta corr  to Alpha corr
0         FAM138A         NaN            NaN
1      AL627309.1   -0.013701       0.013701
2      AL627309.3    0.002729      -0.002729
3      AL627309.2         NaN            NaN
4          OR4F29         NaN            NaN
...           ...         ...            ...
33533      TTTY4B         NaN            NaN
33534       BPY2B         NaN            NaN
33535        DAZ4         NaN            NaN
33536        CDY1         NaN            NaN
33537       TTTY3         NaN            NaN
```
It seems most, but not all, were set to NaN. 

> If you could check out after which operation the Lineage object somehow changes
I'm sorry, but could you clarify this? I checked my post to which this was replying, and perhaps there was some confusion there. I was discussing two different samples: one that only had one metastable / final state and the second with two metastable / final states.

**Comment by timlai4** [comment]
I have downloaded the new version. As you mentioned, the previous function calls no longer work. Now, I am running the following:
```{python}
g.set_final_states_from_metastable_states()
g.compute_absorption_probabilities()
g.compute_lineage_drivers()
```
and with a `print(adata.var.columns)` both before and after for comparison. Again, there is no difference: i.e. no additional columns being added for the lineage drivers.

**Comment by michalk8** [comment]
Hi @timlai4 ,
sorry for the late response. In the object, you `7852` cells and `3000` genes, the `adata.raw` has `33538` genes (i.e. the unfiltered ones). I'd try this first on the not raw data, since raw will most likely containt a lot of 0s.
For only 1 final state, since all cells have absorption probability of 1, I've changed this so we use the stationary distribution when calculating the drivers.
As for 2 or more states, it's the same. I've only changed the default `use_raw=True` (that's the 30k+ genes) to `use_raw=False`.
These changes should be on PyPI shortly.

In the case of 2 states, could you please try running this after `g.compute_absorption_probabilities()` and post here the output?
This is to check whether there's something wrong with the Lineage object or some 0 columns in the expression matrix.
```python
import pandas as pd
from scipy.sparse import issparse

for attr in ("metastable_states_probabilities", "absorption_probabilities"):
    x = getattr(g, attr)
    print(attr)
    print((~np.isclose(x.X.sum(1), 1)).sum(), np.isnan(x.X).sum(0),
          (~np.isfinite(x.X)).sum(0), x.std(0), sep='\n', end='\n\n')

genes = g.adata.var_names
X = g.adata.X
X = pd.DataFrame(X.toarray() if issparse(X) else X, columns=genes)
print(X.columns[X.isna().any(0)],
      X.columns[np.all(np.isclose(X, 0), 0)],
      X.columns[np.isclose(X.std(axis=0), 0)], sep='\n')
```

Here's for example mine:
```python
metastable_states_probabilities
0
[0 0 0]
[0 0 0]
[[0.20456591 0.23479675 0.29189188]]
 names=[std of Epsilon, std of Alpha, std of Beta]

absorption_probabilities
0
[0 0 0]
[0 0 0]
[[0.15492946 0.2254958  0.27272654]]
 names=[std of Epsilon, std of Alpha, std of Beta]

Index([], dtype='object', name='index')
Index([], dtype='object', name='index')
Index([], dtype='object', name='index')
```

**Comment by timlai4** [comment]
Here are the outputs. 
```
>>> for attr in ("metastable_states_probabilities", "absorption_probabilities"):
...     x = getattr(g, attr)
...     print(attr)
...     print((~np.isclose(x.X.sum(1), 1)).sum(), np.isnan(x.X).sum(0),
...           (~np.isfinite(x.X)).sum(0), x.std(0), sep='\n', end='\n\n')
...
metastable_states_probabilities
0
[0 0]
[0 0]
[[0.20181639 0.20181639]]
 names=[std of 17, std of 6]

>>> genes = g.adata.var_names
>>> X = g.adata.X
>>> X = pd.DataFrame(X.toarray() if issparse(X) else X, columns=genes)
>>> print(X.columns[X.isna().any(0)],
...       X.columns[np.all(np.isclose(X, 0), 0)],
...       X.columns[np.isclose(X.std(axis=0), 0)], sep='\n')
Index([], dtype='object')
Index([], dtype='object')
Index([], dtype='object')
```

**Comment by Marius1311** [comment]
@michalk8 for handling this very well. Just one note from my side: when we compute lineage drivers, we check how well lineage probabilities correlate with gene expression for all genes. By default, we used to do this in raw data, i.e. in a version of the AnnData object with usually **all genes** present. In your case @timlai4, it seems that you had ~33k genes in your raw AnnData object. We all know about the large proportion of zero counts in scRNA-seq data. There will be many genes in the raw data with zero expression across all cells. That's why you get the warning message you posted for about 12k genes. There is **nothing wrong with that**, this is expected: for a gene that's zero expressed in all cells, its correlation will be zero. You may safely ignore these genes (i.e. the ones that get a `NaN`) correlation and only look at the remaining genes, as these will be the biologically interesting ones. Or, you do it as @michalk8 suggested and set `use_raw=False`, which I think may even be the default now.

**Comment by Marius1311** [comment]
@timlai4 , is this solved for you, or can we help in any other way?

**Comment by timlai4** [comment]
Sorry for the delay! Yes, I believe I am seeing the appropriate columns after computing lineage drivers now.
