### ISSUE TITLE
Absorption probability plotting

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#307]
The color scale is off when I plot absorption probs. When running `g_fwd.plot_absorption_probabilities(**figure_kwargs)`, I get
![image](https://user-images.githubusercontent.com/24494650/90500943-e17bb880-e14b-11ea-93ef-b4c59f6428f2.png)

Way too many cells are at or near the maximum value and it's impossible to see the gradual changes in probability. When I plot the underlying abs. probs directly using scvelo, i.e. `scv.pl.scatter(adata, c=adata.obsm['to_final_states']['Ciliated activated'], color_map='viridis', dpi=300)`, I get
![image](https://user-images.githubusercontent.com/24494650/90501027-007a4a80-e14c-11ea-8c88-95a95c0d88c7.png)

Which looks much better. I know we had something in the code that takes care of the fact that there are some cells in every lineage which get 1 probability, but I think we were handling this fine in rc0, this bug is new in rc4. What changes between the two versions?

#### Versions:
cellrank==1.0.0-rc.4 scanpy==1.5.1 anndata==0.7.3 numpy==1.18.5 scipy==1.4.1 pandas==1.0.5 scikit-learn==0.22 statsmodels==0.10.2 python-igraph==0.7.1 scvelo==0.2.2.dev51+ga7de78a
> ...

**Comment by Marius1311** [comment]
Okay, note that this problem **only exists** when I plot a single lineage. As soon as I plot two, the color scale is fine again.

**Comment by michalk8** [comment]
Found the culprit, https://github.com/theislab/cellrank/blob/master/cellrank/tl/estimators/_property.py#L553
I needed to distinguish this case because `scv.pl.scatter` (or matplotlib for that sake) was very sensity to the values when there was only 1 lineage (numerically, they were extremely close to 1 (rtol 1e-6), but the colormap still picked up the differences (which is both cool, but undesirable in the case of 1 lineage).
I will add the scaling to 1 as it is in https://github.com/theislab/cellrank/blob/master/cellrank/tl/estimators/_property.py#L560

**Comment by Marius1311** [comment]
We have to distinguish two cases:
1. absorption probabilities were computed for only one lineage
1. absorption probabilities were computed for more than one lineage, but I'm only plotting one.

I'm talking about the second case, I have the feeling you're talking about the first. For the first case, sure, that's a dummy case and we should make sure that every cell has the same color. For the second case, the color of a single lineage should not change whether we plot it individually, or together with other lineages. Do you see my point?

**Comment by michalk8** [comment]
I was talking about the both cases. The 2nd should be fixed now.

**Comment by Marius1311** [comment]
Alright, got it.
