### ISSUE TITLE
Getting gene names from the ordered heatmap

### ISSUE THREAD

**Issue by karlann** [theislab/cellrank#331]
Hey!
I was wondering if there's a convenient way of getting out the ordered gene list from `cr.pl.heatmap()` function? I had a quick look at the code for plotting and what I could gather with my limited understanding of it is that the genes are ordered by seaborn's clustermap, right?

To solve it for myself, I added a few lines to the plotting function to return the clustermap axis object, which I could then query for the tick labels:
```Python
genes = adata.raw.var['to 2 corr'].sort_values(ascending=False).index[:200]
ax = cr.pl.heatmap(adata, model, genes=genes, show_absorption_probabilities=True,
              lineages="2", n_jobs=1, backend='loky', use_raw = True, return_ax = True)

ordered_genes = [x.get_text() for x in ax.ax_heatmap.yaxis.get_majorticklabels()]
```
Am I missing a nicer solution for this?

Thanks!

**Comment by michalk8** [comment]
Hi @karlann ,
currently, there's no easy way of extracting them, but I can add  return it as a dictionary `lineage -> dataframe of sorted genes (with it's clusters)`.
Gene are by default ordered according to the maximum absolute value of the smoothed expression (this produces the plot at the bottom of the basic tutorial), they can be properly clusterered using `cluster_genes=True` (this however breaks the nice ordering and the dendrogram is not show, because labels are on the left, though I will fix that as well).
