### ISSUE TITLE
Handle moment computation for raw anndata object

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#341]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

I often have the following problem: I compute lineage drivers in my raw anndata object. I would then like to look at gene expression trends for the identified genes. However, often, some of the genes identified in the first step are only present in my raw adata object, which means they are not in `adata.layers['Ms']`, which is our go-to for gene expression trends. In these cases, I always have to go back, create a second anndata object which contains all genes, compute moments for this one, copy over absorption probs and then go back to gene expression trend plotting. Is there a better solution to this?

**Comment by michalk8** [comment]
Unfortunately, I don't think of any solution that can solve this, apart from making the negative binomial model ready, here https://github.com/theislab/cellrank/issues/321. This will be a bit of an effor (even when not using David's BatchGLM, becaue I want to replicate the fitting from tradeSeq, which seems robust, at least on their figure. This in turns requires some global information, such as the count matrix to be used and with the current setup, it's not possible. That's why wee need some what I call a bulk fitting method.

**Comment by Marius1311** [comment]
Agenda:
- discuss with David, which backends to include this in.

**Comment by michalk8** [comment]
Closing this in favor of #377
