### ISSUE TITLE
Plotting gene dynamics with cr.pl.gene_trends

### ISSUE THREAD

**Issue by MoritzTh** [theislab/cellrank#37]
Hi guys! I'm trying to reproduce your CellRank pancreas tutorial, but when I try to plot the gene dynamics over latent time with 

`model = cr.ul.models.GamMGCVModel(adata, n_splines=7, sp=100) `
`cr.pl.gene_trends(adata, model=model, data_key='Ms', genes=['Gng12', 'Pak3'], time_key='latent_time', weight_threshold=0.05, weight_scale=1, filter_data=True, dpi=25)`

it's stuck in the loading process (I stopped it after several hours). rpy2 is installed and working properly and switching the model with

`from sklearn.gaussian_process.kernels import RBF`
`from sklearn.kernel_ridge import KernelRidge`
`model = cr.ul.models.SKLearnModel(adata, KernelRidge(kernel=RBF()))`

gives me the same issue. Do you guys have any ideas?

**Comment by michalk8** [comment]
Hey @MoritzTh ,
that's strange. I suspect the progress bar may be somehow stuck because of some strange race condition. I'd try to specify `n_jobs=1` to sequential processing or try `backend='threading'` in `cr.pl.gene_trends`.
Hope this helps. If not, I will add an option to disable the progress bar altogether, since I think the issue lies there.

**Comment by MoritzTh** [comment]
That works, thanks!

**Comment by michalk8** [comment]
Glad it worked!
