### ISSUE TITLE
Need a way to set initial states from metastable states

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#372]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Currently, it's only possible to set the `final_states` from the set of metastable states by using `g_fwd.set_final_states_from_metastable_states`. However, we need the equivalent method for the initial states (also to be set from `g_fwd`). From my point of view, it makes no sense to keep the old terminology on the estimator level, I would consistently rename those to "initial/terminal states" as well. I think having two sets of terms gets confusing, also in the gallery and especially when users switch from the high level to the low level interface.

**Comment by Marius1311** [comment]
We may need to chat about this a bit to clearify the details - fee free to call me tomorrow.

**Comment by michalk8** [comment]
But then essentially 1 function would always be useless (`set_terminal...` when `backward=True` and the opposite). To solve this,
we'd need to have forward and backward object (I could in principle define these functions at runtime, but it will break the docs most likely - i.e. the won't be shown).

**Comment by michalk8** [comment]
I haven't been able to find a suitable name (even asked a friend of mine). My recommendation is to rename `final` to `recurrent` (that's what they are, after all).
Regarding selecting the subset of initial and terminal states, if you really (I mean really, really want this), 
Suggestions:
1.  having still 1 function `set_recurrent_states_from_metastable_states` with 2 parameters `terminal` (required always) and `initial` (optional). For CFLARE, initial must always be empty.
2.  having 2 functions as you've wanted, but keep `set_initial_states_from_metastable_states` be private (I think this is my favorite option, since I think of this as a very niche functionality - you can't do anything with these states [e.g. by setting them in the reverse object], apart from plotting)
3. having 2 functions as above, but the initial is a public one (your original proposition).

I heavily favor the 2nd option - we can easily make it public, if there's a demand. I also assume/hope that there's no need for a plotting function (would have to be again GPCCA specific) for the initial states.
Let me know how you've decided, and I will quickly implement this + rename the final to terminal + make a new release (I will add deprecation warning for the old function `set_final_...` and `plot_final...` - this will be a bit tricky, but I think it's better for the user).

**Comment by Marius1311** [comment]
Hi Mike, re your first comment, that's not _quite_ right, they are _approximatively_ recurrent. If they really were recurrent, then our transition matrix would be reducible. So we would have to call them _approximate_recurrent_states_. That's what I originally called them in CFLARE. 

Option 2 is fine for me. This is mostly a convenience function at the moment.

**Comment by michalk8** [comment]
closed via #383

**Comment by Marius1311** [comment]
Awesome, thanks.
