### ISSUE TITLE
#395 breaks macrostate assignment. 

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#400]
Hi Mike, macrostate assignment seems to have been broken in #395. See below for the pancreas:
![image](https://user-images.githubusercontent.com/24494650/94587163-78c34800-0282-11eb-9e0d-ffc3ca51558b.png)

I thought we have plenty of tests for this sort of thing? We had a lot of trouble with this in the past so we definitely need tests which check in an example whether both name assignment and color assignment match some hard-coded ground truth. Can you come up with something here please?

#### Versions:
cellrank==1.0.0-rc.11 scanpy==1.6.0 anndata==0.7.4 numpy==1.19.1 numba==0.51.0 scipy==1.5.2 pandas==1.1.1 scikit-learn==0.23.2 statsmodels==0.11.1 python-igraph==0.8.2 scvelo==0.2.2 pygam==0.8.0 matplotlib==3.3.1 seaborn==0.10.1
> ...

**Comment by michalk8** [comment]
Fixed in https://github.com/theislab/cellrank/commit/12b42192335c2e42265e88d64d870341b6d0d1a0
+ I've made a new release.
Here's RCA:
I've changed the series to categorical here https://github.com/theislab/cellrank/blob/master/cellrank/tl/_colors.py#L278 (because that's what they are), thinking it doesn't change a thing, since you assign the series to categories.cat.categorieshttps://github.com/theislab/cellrank/blob/master/cellrank/tl/estimators/_base_estimator.py#L778
However, I was mistaken, see the below example:
```python
import pandas as pd
x = pd.Series(['x', 'y', 'z']).astype('category')
z = pd.Series(['d', 'b', 'c']).astype('category')
z.cat.categories  # Index(['b', 'c', 'd'], dtype='object')

x.cat.categories = z
x.cat.categories  #  Index(['b', 'c', 'd'], dtype='object') - same order as in `z.cat.categories`

x.cat.categories = np.array(z)  # Index(['d', 'b', 'c'], dtype='object') - this is what we've expected
x.cat.categories
```
I've changed this so that the order of categories is the same as the order of values (https://github.com/theislab/cellrank/blob/master/cellrank/tl/_colors.py#L279), because it's better to fail early (it will fail if the values are not unique).
On https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.cat.set_categories.html, there's not mention of this, but it seems like a feature rather than a bug, but then again:

```python3
x = pd.Series(['x', 'y', 'z']).astype('category')
z = pd.Series(['d', 'b', 'c', 'c']).astype('category')

# x.cat.categories = z  # throws an error
```
I'd expect also this to work, because the categories match. I will ask on pandas forums.

Why the tests didn't catch it? I wasn't testing on the order of categories, thinking it doesn't matter, since we weren't accessing them anyway (I was testing only for categorical).

**Comment by Marius1311** [comment]
Thanks Mike, I will check this out just now. Did you update the release notes yet?

**Comment by Marius1311** [comment]
Oh, I think you have a typo in the release notes, it should be rc12 at the top, not rc11.

**Comment by Marius1311** [comment]
I can confirm that this works again. Thanks a lot for fixing!
