### ISSUE TITLE
Add parameter of choose basis for scatterplot in two plotting functions tl.terminal_states and plot_macrostates

### ISSUE THREAD

**Issue by DouberZ** [theislab/cellrank#439]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

...

I found there is no function parameter to choose basis or layout for tl.terminal_states and plot_macrostates, while I think it is still necessary to provide the choice to use different basis or layout in the functions. Would you please help with such parameters? 

By the way, as there is no such parameter in the functions at present, could you please tell me if there is anything I can do to change scatterplot basis when plot terminal_states or plot macrostates?

Best regards,
Bo

**Comment by michalk8** [comment]
Hi @DouberZ ,
you can change the basis by specifying `basis=...` in the aforementioned functions, since we're relying on scVelo's scatterplot function to do the actual plotting (see the API: https://scvelo.readthedocs.io/scvelo.pl.scatter.html#scvelo.pl.scatter).
But I think we can expose these in the docstring, any thoughts @Marius1311 ?

**Comment by Marius1311** [comment]
Yes, let's expose the main parameters directly in our docstring, would make a lot of sense I think.
