### ISSUE TITLE
cr.tl.lineages kernel dies repeatedly with 10 lineages but runs with 3 lineages

### ISSUE THREAD

**Issue by DavidvanBruggen** [theislab/cellrank#454]
cr.tl.lineages crashes kernel repeatedly on more than 10 lineages? I can successfully run 3 lineages. Is there any likely culprit? 
The output seems to indicate it starts hanging at the Computing absorption probabilities stage of the script, likely CFLARE or GPCC? 
Is this a bug or specific to me?

Here is the code I use:

```python
cr.tl.lineages(adata)
```
And the output until the kernel dies.

```pytb
Computing lineage probabilities towards terminal states
Computing absorption probabilities
```

#### Versions:

>cellrank==1.1.0 scanpy==1.6.0 anndata==0.7.1 numpy==1.19.2 numba==0.51.2 scipy==1.5.2 pandas==1.1.3 scikit-learn==0.23.2 statsmodels==0.12.1 scvelo==0.2.2 pygam==0.8.0 matplotlib==3.3.2 seaborn==0.11.0

/Many thanks!

**Comment by michalk8** [comment]
Hi @DavidvanBruggen 
might be because a direct solver is being used (and our [heuristics](https://github.com/theislab/cellrank/blob/master/cellrank/tl/estimators/_base_estimator.py#L472) aren't particularly great at picking which solver to use in this case).
If a direct solver is being used, the 2 matrices are densified (I think in case PETSc/SLEPc is installed only 1 is, but that's just minor detail) and this can cause the notebook to crash.

To verify this, you can set the verbosity to debug as `cr.settings.verbosity = 4` (should really be a warning).
If this is the problem, I recommend using an iterative solver like gmres by running `cr.tl.lineages(adata, solver='gmres')` (relevant docs are [here](https://cellrank.readthedocs.io/en/latest/classes.html#cellrank.tl.estimators.GPCCA.compute_absorption_probabilities))

**Comment by DavidvanBruggen** [comment]
Thank you @michalk8 !

The solver indeed was the problem, setting this to solver='gmres' fixed this for me. 

Many thanks!

David
