### ISSUE TITLE
how to deal with batch effect

### ISSUE THREAD

**Issue by wangmhan** [theislab/cellrank#461]
Hi,

I want to ask for your suggestions how to deal with batch effect. I have samples from 3 time points, and did batch correction for the expression matrix. For the spliced and unspliced counts just kept as it is. Then I run cellrank with the integrated 3 samples together, and also each sample independently, all using the same embedding. The result of scv.pl.velocity_embedding_stream changed a lot. The integrated one looks similar to one sample with more cells then the other two, don't know if this is the proper reason for that. 
I saw a webpage also make discussion about the batch effect in spliced and unspliced counts (https://www.hansenlab.org/velocity_batch). Do you think it make some sense? If so, what is the solution? I tried to use combat, but struggle a bit with the ratio of spliced to unspliced as don't know how to handle when unspliced is 0. Is it ok to just add 0.001 to both, or have better operation?

Thank you!

**Comment by Marius1311** [comment]
Hi @wangmhan, this is a great question, and one that I have been thinking of myself, together with others in the lab, e.g. @VolkerBergen. 

Generally speaking, when you have time-series data, you need to keep in mind timescales. RNA velocity approximates the first derivative of gene expression and can be used to linearly extrapolate a cell's current state into the _near future_. Now, how long is that _near future_? That depends on your biological process, in particular, it depends on the timescale on which a linear extrapolation makes sense. In the particular case of chromaffin differentiation at E12.5, the authors of the original RNA velocity publication (La Manno et al., 2018, Nature) show that this timescale is in the range of 2.5 - 3.8h. Does that mean that you can only use time-series datasets where sampling has been done every 2h? No, certainly not, because there is asynchrony within each time point - the old concept that we have been using in the field since the first pseudotime methods came about in 2014. So as long at the underlying phenotypic manifold is connected across time points because of asynchrony and relatively dense sampling, you can use time-series datasets. RNA velocity will give you linear extrapolations that can be used to link gene expression profiles together on short time scales - CellRank takes it to the global timescale for you by linking together many individual small transitions. 

However, there are limits to this: if you have one time points every 4 days, then RNA velocity will most likely not work when you apply it to the combined dataset - the "gaps" are just too large. So, the first questions you should ask yourself is whether it even makes sense to use RNA velocity here. Is your sampling dense enough, and do you expect to see a lot of asynchrony within each time point?

**Comment by wangmhan** [comment]
Hi Marius,

Thank you for your reply. I understand if the interval is too large, it
will not make so much sense to run velocity.
But in my case, the interval is around 24 hour. And when we look at the
embeddings, the cells from different developmental stages are
mixed together. We do see heterogeneity in each time point. And the
unspliced ratio ranges from 12% to 18%.

I think the major questions I would like to ask here is, should I trust the
velocity I got from the integrated data? Although it looks different if I
run velocity separately for each stage.....

**Comment by Marius1311** [comment]
Hi @wangmhan, this is a really difficult question, and I think it relates more to velocities then it does to CellRank. Therefore, I think it would make sense to move this question to the [scvelo](https://github.com/theislab/scvelo/issues/new?assignees=&labels=question&template=general_question.md&title=) repository where you should get more targeted support.

**Comment by wangmhan** [comment]
Sure, thank you.

**Comment by Marius1311** [comment]
You're welcome! I will close this issue here.
