### ISSUE TITLE
Where is Delta terminal state?

### ISSUE THREAD

**Issue by LouisFaure** [theislab/cellrank#554]
Dear CellRank maintainers, 

I lately went back to your package after the latest updates you have made, but I have memories of earlier versions having tutorial of the Pancreas dataset where 4 terminal states were found, with Delta cells included. The plot on the homepage of the documentation actually still shows such result.

But now by trying to reproduce the notebooks, it is impossible to recover the Delta lineage, it seems that it has been now captured in the Beta lineage. What could explain such phenomenon?

Cheers!

**Comment by Marius1311** [comment]
Hi @LouisFaure! Thanks for your question. Using a combination of velocity and similarity information, we cannot automatically find the Delta macrostate and detect it as a terminal state - not before the 1.3 update and not after, nothing changed in this regard in our latest release. What is however possible it to compute a few more macrostates (e.g. 12, as in our [preprint](https://www.biorxiv.org/content/10.1101/2020.10.19.345983v2)) until the Delta state is among them and to then assign it terminal status manually,  see [this example](https://cellrank.readthedocs.io/en/stable/auto_examples/estimators/compute_terminal_states_gpcca.html#sphx-glr-auto-examples-estimators-compute-terminal-states-gpcca-py). Thinking back, I suppose this is what we did in an earlier version of the tutorials you're referring to. You can still do this, nothing has changed. 

You may wonder why it is not possible to automatically detect the terminal Delta state here. We show in the preprint (linked above) that this is likely due to insufficient unspliced counts in key delta driver genes like Cd24a, see Supplementary Fig. 11 in the preprint. As you might recall, RNA velocity is based on the ratio of spliced to unspliced counts. Unspliced counts are more difficult to detect in the cell, and for some genes, this just doesn't work very well (there are some causes for this and one can dig a bit deeper if needed). Combine this with the fact that there are only 80 Delta cells present in this data and you get to a situation where we can detect Delta as a metastable mactostate, but not automatically as terminal. I hope this answered your question.

**Comment by Marius1311** [comment]
@LouisFaure, I suppose the above answers your question and will close this issue - feel free to re-open this if something is still unclear.

**Comment by LouisFaure** [comment]
@Marius1311 Thank you very much for the explanation it is all clear now!
