### ISSUE TITLE
Refactor estimators

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank#564]
- [ ] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [x] Other?

TODOs:
- [ ] rephrase it as a stateful machine (easier to handle IO from/to adata)?
- [ ] remove `PropertyMeta` (was used during development due to frequent naming changes)
- [ ] related to ^, get rid of https://github.com/theislab/cellrank/blob/master/cellrank/tl/estimators/_constants.py
- [ ] change default tolerance for solvers in abs. prob. calculation/add preconditioner?
- [ ] allow option to serialize self to a file without `anndata`

**Comment by Marius1311** [comment]
For the preconditioners, we should probably do a quick benchmark, i.e. take the three datasets we have on Figshare and compare `gmres` with and without preconditioner to the direct solver. Our assumption here is that the direct solver gives us ground truth. Probably, we can't do this for the morris data because it's way too large for the direct solver.

**Comment by Marius1311** [comment]
Hi @michalk8, what's a realistic timeline for this?

**Comment by michalk8** [comment]
> Hi @michalk8, what's a realistic timeline for this?

Next week.

**Comment by michalk8** [comment]
closed via #727

**Comment by Marius1311** [comment]
This is hughe, thanks everyone!!! Esp. thanks to @michalk8 for this heroic effort!
