### ISSUE TITLE
Set initial state for pseudotime without RNA velocity information

### ISSUE THREAD

**Issue by tbrunetti** [theislab/cellrank#576]
...
I am trying to use our dataset to calculate pseudotime and get drivers and gene expression trends.  We do not have RNA velocity because it does not work well with out data set. Therefore, I am going through the tutorital provided by your readthedocs site "Beyond RNA velocity".

We notice that using:
```
ctk = CytoTRACEKernel(adata)
```
estimates that the earliest initial state is not correct.  Is there a way to set the initial state to a particular cluster of cells before it runs the pseudotime analysis?  I would like to generate the graph produced by running `scv.pl.velocity_embedding_stream()` however, just change the initial state.

**Comment by Marius1311** [comment]
Hi @tbrunetti, if you have a good notion of where your initial state is, I recommend the following workflow
1. Compute a pseudotime using whatever tool you like. Popular choices for pseudotime analysis tools include [DPT](https://scanpy.readthedocs.io/en/latest/api/scanpy.tl.dpt.html#), [Monocle](https://cole-trapnell-lab.github.io/monocle3/), [Palantir](https://github.com/dpeerlab/Palantir) or [slingshot](http://www.bioconductor.org/packages/release/bioc/html/slingshot.html). In general, I would recommend [scVelo's latent time](https://scvelo.readthedocs.io/DynamicalModeling.html), however, that does not apply in your case because you mentioned RNA velocity does not work well in your case. Please note that this first step is independent of CellRank - you can use your favourite pseudotime tool here. 
2. Now we switch to using CellRank. Use a [`PseudotimeKernel`](https://cellrank.readthedocs.io/en/stable/classes.html#pseudotime-kernel) based on the pseudotime you computed in step 1. If you're unfamiliar with the concept of kernels in CellRank, please make sure to go through our [kernels and estimators](https://cellrank.readthedocs.io/en/stable/kernels_and_estimators.html) tutorial first. With the `PseudotimeKernel`, you can get the same embedding streamline plot you requested as with the [`CytoTraceKernel`](https://cellrank.readthedocs.io/en/stable/classes.html#cytotrace-kernel). The methods have the same names, all kernels inherit form the same base kernel class. 
3. Now continue your analysis by initializing an [`estimator`](https://cellrank.readthedocs.io/en/stable/classes.html#estimators) based on the `PseudotimeKernel` and proceed as always with computing macrostates, terminal states, gene expression trends, driver genes, etc. CellRank is build in a [modular fashion](https://cellrank.readthedocs.io/en/stable/kernels_and_estimators.html) so that our estimator objects work regardless of how you computed the transition matrix, i.e. whether you used RNA velocity, pseudotime, spatial proximity, optimal transport, CytoTRACE, etc. does not matter. 

I'm recommending this workflow because the `CytoTraceKernel` does not permit you to provide an initial state whereas this is possible by first computing a pseudotime using e.g. DPT and then computing a transition matrix based on this pseudotime using the `PseudotimeKernel`.  Note that DPT and Palantir are python-based whereas Monocle and slingshot are in R.

**Comment by tbrunetti** [comment]
Thank you so much!  This makes perfect sense, and thank you for modularizing cellRank!  Many software packages are not coded up this way, so this is really nice.  I have already played around with Monocle and slingshot, so for the sake of trying something new, I will try DPT or Palantir to compare results. 

Now, out of curiosity, if we had not know the initial state of our cells, how valid are the pseudotime estimates (without RNA velocity but using the same process of your Beyond Velocity tutorial) compared to forcing and initial state using a separate pseudotime algorithm, assuming the transition matrix is indeed stable?

**Comment by Marius1311** [comment]
Hi @tbrunetti, that's really a dataset-dependent question I would say. In general, for a comparison among pseudotime algorithms, please check out [Saelens et al., Nature Biotech 019](https://www.nature.com/articles/s41587-019-0071-9). 

I would argue as follows, but that's really just my personal take on this:
- if you have a dataset with a single initial state representing normal, healthy development and **you know** this initial state, I would compute a pseudotime using any of these many published methods, and choose the one that gives you a pseudotime that matches your bio expectations best. 
- if you have a dataset where you either expect many initial states, or you don't know where the initial state(s) are, then I would recommend using the `CytoTraceKernel`. Please note the kernel contains a reimplementation of the original method published in [Gulate et al., Science 2020](https://science.sciencemag.org/content/367/6476/405), this is not our work. Please see their paper for more info. However, the `CytoTraceKernel` does not stop with this reimplementation, it takes the score and uses it to bias a KNN graph such that edges point into the direction of decreasing differentiation potential, or, equivalently, increasing `ct_pseudotime`. 

So if you want to judge how valid the results of the `CytoTraceKernel` are, then I would recommend checking whether the biological assumption formulated in CytoTRACE holds for your dataset, i.e. whether less mature cell types on average express more genes (simply plot `'ct_num_exp_genes'`, maybe averaged per cluster). Of course, you can only do this if you at least have a vague idea of mature/less mature cell types/states in your data. However, in most systems, that will be the case, and you only need to know this on a per-cluster level, not for each individual cells. Hope that helped!

**Comment by tbrunetti** [comment]
Thank you this helps out a lot.  I will also check out these papers.  Thank you so much!!!
