### ISSUE TITLE
Embedding stream interpretation

### ISSUE THREAD

**Issue by leomorelli** [theislab/cellrank#585]
Hi everyone! I'm trying to create a new kernel, using the function provided in your tutorials:
`class MyKernel(cr.tl.kernels.Kernel):

    def compute_transition_matrix(self, my_matrix) -> "MyKernel":
        transition_matrix =my_matrix
        self._compute_transition_matrix(transition_matrix, density_normalize=True)
        return self

    def copy(self) -> "MyKernel":
        return copy(self)`
After having obtained the transition matrix, I have followed the tutorial "Kernels and Estimators" present on your readthedocs page, untill I have obtained macrostates:

![macrostate_discrete](https://user-images.githubusercontent.com/57952505/117662003-5b067b80-b19f-11eb-858c-f219bfdbc1ba.png)

At first I was exctited because I thought my matrix had some kind of sense; however, I have decided to look at the embedding stream, through the function `scv.pl.velocity_embedding_stream(adata,vkey='T_fwd',color='clusters')` and I have soon realized that something was obviously wrong.

![embedding_stream](https://user-images.githubusercontent.com/57952505/117662887-59898300-b1a0-11eb-814d-9d110139d912.png)
Even if I am conscious of the fact that my model has some problems, I was wondering if there is a sort of explanation to these results and how can I interpret the shape of such streams of differentiation.

**Comment by Marius1311** [comment]
Hi @leomorelli, that's an excellent question - we've seen similar kinds of results using the `PseudotimeKernel` with the `hard` thresholding scheme. However, when we looked into this via simulation of trajectories, the problems disappeared, i.e. the simulated trajectories did follow the expected trends. Could you do the same and post the results here? I.e. simulate some trajectories as demonstrated in the [CellRank beyond RNA velocity](https://cellrank.readthedocs.io/en/stable/beyond_rna_velocity.html) tutorial, starting from e.g. the Ngn3 low EP cluster and see where they go. Don't simulate too many, maybe like 10, otherwise it gets messy and hard to interpret.

**Comment by Marius1311** [comment]
Yes, you seem to have jumps to cells that are very distant in the UMAP, which we shouldn't overinterpret but probably means that there are problems with your transition matrix. To be sure, I would recommend you do the same thing now based on a regular `VelocityKernel` and compare. I expect you shouldn't see these jumps then.

**Comment by dawe** [comment]
@Marius1311 one question on transition matrices, then. Should they be thresholded somehow or is it ok to have complete matrices (as long as such jumps are weighted much less than adjacent transitions)? Also, is tril/triu needed?

**Comment by dawe** [comment]
@Marius1311 Yes, please
