### ISSUE TITLE
Trajectory plotting doesn't recognize passed starting cells when called the first time

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#612]
I call `wk.plot_random_walks(n_sims=300, max_iter=200, start_ixs={'day': '0.0'}, basis='force_directed', c='day', 
                     legend_loc="none", linealpha=1, dpi=150)`
Whenever I call this method for the first time, I get the following warning: 
```python
WARNING: No start indices have been selected, using `None`
```
the corresponding plot indeed shows random starting cells. When I call the method again, all is fine and the passed starting cells are used correctly. 

#### Versions:

> cellrank==1.3.1+ga966e79 scanpy==1.7.2 anndata==0.7.5 numpy==1.19.2 numba==0.51.2 scipy==1.5.3 pandas==1.2.1 pygpcca==1.0.2 scikit-learn==0.24.0 statsmodels==0.12.1 python-igraph==0.8.3 scvelo==0.2.3 pygam==0.8.0 matplotlib==3.3.3 seaborn==0.11.0

**Comment by michalk8** [comment]
I think the problem is that WOT kernel requires float categories (it also writes them back to adata). If the original categories were e.g. ints or strins, this might be it.

**Comment by Marius1311** [comment]
Okay, can we prevent this from happening on our side, i.e. by changing the dtype when initializing the kernel?

**Comment by michalk8** [comment]
> Okay, can we prevent this from happening on our side, i.e. by changing the dtype when initializing the kernel?

We only require 2 things when initializing the exp. time kernel:
- that it has a numeric dtype
- that the categories are ordered

WOT, in addition, requires the dtype to be precisely `float` and it also has to write this (possibly) transformed time back to adata (because it reads from it later) - the latter is not the case for exp. time kernel.

I will try once more to reproduce this on the lung data, but as far as I'm concerned, it's working as intended (in the code above, you should've passes `start_ixs: 0.0`) and if there's no bug, I am going to close this.

**Comment by Marius1311** [comment]
Okay, let's close this for now, if I see the same in other datasets, I will re-open. Thanks for looking into this!
