### ISSUE TITLE
Use cr.pl.cluster_lineage with cluster labels

### ISSUE THREAD

**Issue by hspitzer** [theislab/cellrank#629]
I’m currently using CellRank to analyse different expression patterns along a lineage. For this, I use `cr.pl.cluster_lineage`. While this function already shows a lot of the information we need, I was wondering if its possible to add information about the cluster values at the bottom, as possible with `cr.pl.heatmap` using the `cluster_key` argument.
I looked at the code a bit, but was not able to plot the cluster colors myself, as the clustering step also resamples the x values into uniformly spread `test_points`. 

I would be happy for any suggestions of how to plot lineage gene expression for a set of genes with cluster information attached!

**Comment by michalk8** [comment]
Did you mean something like this, @hspitzer ? This shows all cluster labels within the `[tmin, tmax]`, where the model was fit, not only the labels at the resampled points (or points closest to the resampled points), as done in `cellrank.pl.heatmap` - there I believe it's necessary because of `seaborn`, would have to recheck.
![cluster_lin](https://user-images.githubusercontent.com/46717574/123529305-75a89b80-d6de-11eb-9051-78adaa1eeed8.png)

The code is currently on `cluster_lin_clusters` branch. 2 questions:
- do you also want to visualize multile keys in `adata.obs`?
- do you want the ratio exposed (currently, it's `0.1`) - might be needed if the above is desired

**Comment by michalk8** [comment]
I've added an option to plot more than 1 covariates, it's called `covariate_key`.
closed via #634

**Comment by hspitzer** [comment]
Thanks a lot @michalk8! This is exactly what I was hoping for! I'll try this out asap on my own data. 
I was only thinking about one categorical value, but for the future plotting several might be very useful!

One question though, do the cluster labels reflect the current lineage? E.g. if I have a branching point somewhere on the lineage, are the cluster labels plotted here corresponding to the lineage that I am currently looking at?

**Comment by michalk8** [comment]
@hspitzer 
> One question though, do the cluster labels reflect the current lineage?

No, we never do any hard-assignment of cells to lineages.

**Comment by JesseRop** [comment]
Is it possible to include the legend for the variables added with the `covariate_key` ?

**Comment by michalk8** [comment]
> Is it possible to include the legend for the variables added with the covariate_key ?

Currently, this is not possible. If you'd like to have this feature included, please open an issue for this.
