### ISSUE TITLE
Number of neighbors considered in PseudoTimeKernel

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#669]
## Description

This issue picks up the discussion from #603 on whether or not to used symmetrized number of neighbors in `PseudoTimeKernel`. ATM, the `PseudoTimeKernel` only considers the unsymmetrized number of neighbors instead of the observation-specific symmetrized one as in `ConnectivityKernel`. As I understood, this is due to trying to mimic the behavior of `Palantir` as much as possible. One option would be using the symmetrized number of neighbors and include a `Palantir` specific kernel.

**Comment by Marius1311** [comment]
For this, we discussed a benchmarking strategy in our last meeting based on predicting fate outcome for lineage-traced data.

**Comment by Marius1311** [comment]
Benchmarking task (@michalk8):
- check in reprogramming data (morris) & hematopoiesis data (klein) how well we can predict ground truth fate choice, e.g. prediction task against lineage tracing labels.

**Comment by michalk8** [comment]
@Marius1311 just to be sure, we want to have symmetric sparsity pattern by symmetrizing the biased connectivities, right?

**Comment by Marius1311** [comment]
Yes, symmetric sparsity pattern, the actual values will of course be non-symmetric. 

In scanpy, when you run `sc.pp.neighbors`, the added `distances` attribute represents the raw, non-symmetrized distances, i.e. each cell will have *exactly* K neighbors. In contrast, the added `connectivities` attribute represents a transformed, symmetrized version of the distances. The transformation depends on the `method` parameter, and can be e.g. `umap` or `gauss`.

**Comment by Marius1311** [comment]
This is very easy to do, you just consider the non-zero entries in `connectivities` as the neighbors, rather than the non-zero entries in `distances`.

**Comment by michalk8** [comment]
So in essence [this](https://github.com/theislab/scanpy/blob/master/scanpy/neighbors/__init__.py#L887-L892), right?

**Comment by Marius1311** [comment]
No, we don't need to symmetrize on our end, just use directly the indices from the connectivity matrix.

**Comment by Marius1311** [comment]
For method `gauss`, that should be it, yes. We don't need to worry about this on our end, as long as we use the indices provided in the connectivity matrix, we can assume they are symmetric. We can also check for this, we have a check in our utils.

**Comment by michalk8** [comment]
@Marius1311 based on what we've discussed today:
Morris data result (pseudotime was taking from palantir, terminal states are from our revision and are fixed):
new (locally taking the `n_neighs`):
![local_res](https://user-images.githubusercontent.com/46717574/132568880-9642ea12-3a48-4e8f-8604-4a85c3de4335.png)
old (current approach):
![global_res](https://user-images.githubusercontent.com/46717574/132568906-29aaef60-8b9b-44ba-b40e-9c039de09283.png)
hematopoiesis (DPT, also fixed term. states from previous run)
new (`Abs. prob: 0.046030676809634845, Comm: 0.3043874927638428`):  
![hema_new_disc](https://user-images.githubusercontent.com/46717574/132570446-6ad5a9c1-1225-449c-a3d3-63d7942bac23.png)
![hema_new](https://user-images.githubusercontent.com/46717574/132570449-bb8ef378-d770-4a8a-9038-a4c4794d1811.png)
old (`Abs. prob: 0.044681092837939154, Comm: 0.27874944946221464`):
![hema_old_disc](https://user-images.githubusercontent.com/46717574/132570427-212560ca-dd66-463a-bf25-e83766b31794.png)
![hema_old](https://user-images.githubusercontent.com/46717574/132570430-0b1d39e1-2f12-4d2e-8050-664fd489f791.png)


Result: I see no strong evidence of taking `n_neighs` locally instead of our current approach (only in the 2nd case it marginally helps).

**Comment by Marius1311** [comment]
Thanks Mike! Since taking the number of neighbors locally seems more naturally to me, I would vote for changing the current implementation to that.

**Comment by michalk8** [comment]
Shall we keep the current option or just get rid of it completely?

**Comment by michalk8** [comment]
Also, I remember having a discussion about this a long time ago, but I can't find the issue (maybe it's in one of the older repos)...

**Comment by michalk8** [comment]
> Shall we keep the current option or just get rid of it completely?

Think it makes sense not to overwhelm the user (in any case, can reintroduce in a future PR).
closed via #738

**Comment by Marius1311** [comment]
Agreed, let's get rid of the old option.
