### ISSUE TITLE
Binder Kernel died either on or just before `velocity_graph` of basic tutorial

### ISSUE THREAD

**Issue by adamgayoso** [theislab/cellrank#694]
Hello,

I tried running the cellrank tutorial via binder and the kernel died. I also had some trouble getting the tutorial started (had to close after a few minutes as environment wasn't built properly and refreshing worked). Is colab a better solution for these tutorials?

<img width="1164" alt="Screen Shot 2021-08-06 at 12 51 55 PM" src="https://user-images.githubusercontent.com/10859440/128564282-e17bf29d-c8bc-4309-8541-da84c10fcce5.png">

**Comment by michalk8** [comment]
Hi @adamgayoso ,
looks like you've gotten a rather small-ish machine (only 2GBs) - I got lucky (8GBs) and it worked, see the screenshot below:
![binder](https://user-images.githubusercontent.com/46717574/128569538-cf03c8fb-9eaa-4bdf-b83b-0912ff96f275.png)

> I also had some trouble getting the tutorial started (had to close after a few minutes as environment wasn't built properly and refreshing worked). Is colab a better solution for these tutorials?

As for environment taking too much time, I wasn't aware of this issue (atm, there's only 1 requirement that could be removed, since it's only needed in 1 of the tutorials [the `WOT` package]). With colab I have no experience, so I can't tell if it would be better.

**Comment by Marius1311** [comment]
I personally think collab would be better, I've encountered similar issues to @adamgayoso using binder to load our tutorials.

**Comment by adamgayoso** [comment]
Colab is nice, a little uglier than Binder, but always works... unless you have R things you need to demonstrate.

**Comment by michalk8** [comment]
Does collab always require you to log-in into a Google account? I've tried running one notebook from `scvi-tools` and it always prompts me to log-in. If yes, unfortunately, this is a dealbraker for me.

**Comment by adamgayoso** [comment]
Indeed it does. Is your concern privacy? For what it’s worth, many many
universities here use google to power email, etc.

**Comment by adamgayoso** [comment]
At the very least, a compromise is to offer badges for both services?

**Comment by michalk8** [comment]
> At the very least, a compromise is to offer badges for both services?

You're right, as long as there's an option to choose from, I think it's fine.

**Comment by michalk8** [comment]
There were some issues (see #707), but otherwise, the colab should be enabled on the `latest` (once the docs are up).
