### ISSUE TITLE
Auto-generated release notes too long

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#734]
The auto-generated release notes for #696 include a line with more than 120 characters breaking the linting check in the CI.

#### Versions:

> cellrank@dev

**Comment by WeilerP** [comment]
@michalk8, any idea how to prevent this in the future? Also, maybe we should run the linting job in the CI when release notes are added by towncrier to prevent this kind of thing from happening in the future?

**Comment by michalk8** [comment]
> @michalk8, any idea how to prevent this in the future? Also, maybe we should run the linting job in the CI when release notes are added by towncrier to prevent this kind of thing from happening in the future?

There's `rstcheck` in place for both news fragment and new dev release notes, this is `doc8`'s "fault".
2 solutions:
1. in `docs/source/create_news_fragment.py`, when parsing the message, ensure it has a certain line length (like 80 max, just in case)
2. the easier solution: disable some `flake8` checks in the autogenerated stuff in `tox.ini`

Re linting: I didn't want to run full linter since a lot of useless checks are done, not relevant to `.rst` files + in the future, I want to have `tox -e check-docs` (like in `squidpy`) which would be more stringent (essentially runs link+spellcheck).

**Comment by michalk8** [comment]
closed via #735 (the spellcheck/linkcheck will addressed in a separate issue).
