### ISSUE TITLE
is there an option for `g_fwd.compute_lineage_drivers` to not return the dataframe? 

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#753]
Used to work via `return_drivers=False`, but seems to no longer work .

**Comment by michalk8** [comment]
Yes, I've removed this and kept it returning because we also sort the values on return - the stored ones in `adata.varm` cannot be sorted (unless we sort the whole adata object).
This was done purely for consistency+convenience (i.e. see the correlated values immediately instead of accessing some field).

**Comment by Marius1311** [comment]
ok, fine.
