### ISSUE TITLE
Multi-flow plot

### ISSUE THREAD

**Issue by kaplinserm** [theislab/cellrank#832]
...
Hello,
First, thank you so much for your work on cellrank, it's a very useful tool.
Do you plan to implement the multi-flow plot ? I think it will be an extraordinary tool and I am willing to test it on my data if you need, I want to use it in my paper.
Best

**Comment by michalk8** [comment]
Hi @kaplinserm ,

thank you for your interest! The current implementation in https://github.com/theislab/cellrank/tree/plot_multiflow was/is still a work-in-progress, since in our internal benchmarks, we were dissatisfied with how internal model (simple aggregation base on clusters/time points) was being done (@Marius1311 can tell you more). We haven't found another method yet, so this is currently on hold, but in the future, we'd be happy to continue working on this.

**Comment by Marius1311** [comment]
Sorry, just saw this issue, already commented in the PR, but let's move the discussion here. Basically, @kaplinserm, let us know if you have ideas for how to do this a bit more systematic/principled, happy to hear your ideas.

**Comment by Marius1311** [comment]
I'll close this for now but we might want to reconsider this for moslin @michalk8
