### ISSUE TITLE
cr.tl.lineages- ValueError: `2464` value(s) do not sum to 1 (rtol=1e-3)..

### ISSUE THREAD

**Issue by bsmith030465** [theislab/cellrank#834]
Hi,

I was trying to use cr.tl.lineages:

`cr.tl.lineages(adata)`

but get the following error:

`<string>:1: DeprecationWarning: `cellrank.tl.lineages` will be removed in version `2.0`. Please use the `cellrank.kernels` or `cellrank.estimators` interface instead.
Computing absorption probabilities
100%|██████████| 3/3 [01:22<00:00, 27.48s/]
WARNING: `1` solution(s) did not converge
ValueError: `2464` value(s) do not sum to 1 (rtol=1e-3). Try decreasing the tolerance as `tol=...`, specifying a preconditioner as `preconditioner=...` or use a direct solver as `solver='direct'` if the matrix is small.`

I also tried with:
`cr.tl.lineages(adata, tol=1e-07)`

but get the same error. 

How do I resolve this error?

thanks!

**Comment by michalk8** [comment]
Hi @bsmith030465 ,
can happen when the matrix is badly conditiond; could you also try `preconditioner='ilu'` and see whether it helps? Also, the default `tol` is `1e-6`, so decreasing it further might also work. related issue #812 
Lastly, please consider using the kernels/estimators API mentioned [here](https://cellrank.readthedocs.io/en/stable/kernels_and_estimators.html), this one will be deprecated soon

**Comment by bsmith030465** [comment]
Hi @michalk8 ,

I tried both the options you suggested, before moving onto using the kernels/estimators (as given in the API). I run into the same errors. Here is what I have tried so far:

`g.compute_absorption_probabilities(tol=1e-15) 
g.compute_absorption_probabilities(preconditioner='ilu')
g.compute_absorption_probabilities(preconditioner='ilu',tol=1e-15)
g.compute_absorption_probabilities(solver='direct')`

I still get the same errors:

`WARNING: `1` solution(s) did not converge
ValueError: `2464` value(s) do not sum to 1 (rtol=1e-3). Try decreasing the tolerance as `tol=...`, specifying a preconditioner as `preconditioner=...` or use a direct solver as `solver='direct'` if the matrix is small.`

**Comment by michalk8** [comment]
Could you please tell me:
- how many cells you have in your data?
- how did you compute the transition matrix, i.e. which kernel did you use?
- do you use PETSc/SLEPc (`import petsc4py; import slepc4py`)? Based on the above, I'd say yes, just want to be sure  (the `preconditioner` works only in this case)
- how did you select the terminal states, i.e. manually set or computed?

Regarding the last point, it can happen the problem is too hard to solve (most likely due to numerical instability) when the terminal states go agains the "flow" of the transition matrix.
As an example in the pancreas data using in the basic/kernels & estimators tutorial, if I select the terminal states to be cells from `Ngn3 low EP`, but the transition matrix was computed for the forward process (based on RNA velocity) as:
```python
adata.obs['term_states'] = adata.obs['clusters'].cat.remove_categories(
    [c for c in adata.obs['clusters'].cat.categories if c != 'Ngn3 low EP']
)

g.set_terminal_states(adata.obs['term_states'])
g.compute_absorption_probabilities(preconditioner='ilu')
```
I also get the following error:
```pytb
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_78879/4137473892.py in <module>
      2 
      3 g.set_terminal_states(adata.obs['term_states'])
----> 4 g.compute_absorption_probabilities(preconditioner='ilu')

/opt/projects/helmholtz/cellrank/cellrank/tl/estimators/mixins/_absorption_probabilities.py in compute_absorption_probabilities(self, keys, solver, use_petsc, time_to_absorption, n_jobs, backend, show_progress_bar, tol, preconditioner)
    292             axis=1,
    293         )
--> 294         abs_probs = self._compute_absorption_probabilities(
    295             q,
    296             s,

/opt/projects/helmholtz/cellrank/cellrank/tl/estimators/mixins/_absorption_probabilities.py in _compute_absorption_probabilities(self, q, s, trans_indices, term_states, solver, use_petsc, n_jobs, backend, tol, show_progress_bar, preconditioner)
    433         mask = np.isclose(abs_classes.sum(1), 1.0, rtol=1e-3)
    434         if not np.all(mask):
--> 435             raise ValueError(
    436                 f"`{np.sum(~mask)}` value(s) do not sum to 1 (rtol=1e-3). Try decreasing the tolerance as `tol=...`, "
    437                 f"specifying a preconditioner as `preconditioner=...` or "

ValueError: `2393` value(s) do not sum to 1 (rtol=1e-3). Try decreasing the tolerance as `tol=...`, specifying a preconditioner as `preconditioner=...` or use a direct solver as `solver='direct'` if the matrix is small.
```

Have you tried visualizing the transition matrix e.g. using a streamplot as described [here](https://cellrank.readthedocs.io/en/stable/auto_examples/kernels/plot_projection.html#sphx-glr-auto-examples-kernels-plot-projection-py) or using [random walks](https://cellrank.readthedocs.io/en/stable/auto_examples/kernels/plot_random_walks.html#sphx-glr-auto-examples-kernels-plot-random-walks-py)? The former works only in a certain cases though (like using a connectivity-based kernel).

I see in your example that you have 3 terminal states (correct me if I'm wrong) and the solution for only 1 failed to converge - if I were you, I'd investigate which one of these states is the culprit)

**Comment by Marius1311** [comment]
I'm a bit confused here - @michalk8, you said at the top 
> "Also, the default tol is 1e-6, so decreasing it further might also work."

Wouldn't *decreasing* the tolerance make it even harder? That's also what our current error message seems to suggest, but wouldn't it make more sense to *increase* the tolerance? Also, I think it would be nice for debugging to print in the error message how *far from one* we are in the worst case, i.e. the max deviation across all rows.

**Comment by Marius1311** [comment]
But in this case, I guess the problem originates from one linear solve not converging? In which case I agree @michalk8 we need to know more about the problem/ the transition matrix to diagnose this.

**Comment by michalk8** [comment]
I assume this has been solved, if not, please re-open.

**Comment by monica-nicolau** [comment]
Hi everyone!
I got the same error as @mbensouda:
`ValueError: '7387' value(s) do not sum to 1 (rtol=1e-3). Try decreasing the tolerance as 'tol=...', specifying a preconditioner as 'preconditioner=...' or use a direct solver as 'solver='direct' if the matrix is small.`

I tried to set `preconditioner='ilu'` and I also tried several `tol` values, such as 1e-3, 1e-8 and 1e-10.

Is there a way to address this issue?

Thanks!

**Comment by Marius1311** [comment]
Hi @monica-nicolau, would there be a way to provide us with an example to reproduce this bug? Either here, or via email to info@cellrank.org. That would massively help us!

**Comment by monica-nicolau** [comment]
Hi all!
I managed to avoid the `SVD did not converge` error setting `enforce=True` during the normalization process carried out through `scv.pp.filter_and_normalize(adata, enforce=True)`. Still, I'm not sure why this is working, but I guess it's because this particular condition was an ill-conditioned matrix. 
Thanks!

**Comment by Marius1311** [comment]
Are you sure you're passing the `enforce=True` to `scv.pp.filter_and_normalize`?

**Comment by monica-nicolau** [comment]
After I add `enforce=True`, I don't get the error message anymore :)
