### ISSUE TITLE
Issue using dimensionality reduction in compute_transition_matrix for WOTKernel on imported single cell experiment

### ISSUE THREAD

**Issue by schmeing** [theislab/cellrank#868]
While trying to compute the transition matrix with the WOTKernel with the following command (tutorial code adapted to my own data):
```python
wk.compute_transition_matrix(growth_iters=3, growth_rate_key="growth_rate_init", last_time_point="connectivities", use_highly_variable ="HVG_CD8")
```

I get the following output including a warning:
```pytb
Computing transition matrix using Waddington optimal transport
Using `1003` HVGs from `adata.var['HVG_CD8']`
Using default cost matrices
Computing transport maps for `4` time pairs
100%
4/4 [29:51<00:00, 450.17s/time pair]
    Finish (0:29:51)
WARNING: You’re trying to run this on 20057 dimensions of `.X`, if you really want this, set `use_rep='X'`.
         Falling back to preprocessing with `sc.pp.pca` and default params.
Computing transition matrix based on `adata.obsp['connectivities']`
    Finish (0:00:00)
Using `threshold=0.006587337711858468`
    Finish (0:33:38)
```

I assume it is about calculating of the connectivities for the last time point. Thus, I tried to add the parameter:
```python
 use_rep='PCA'
```

However, then I get an error:
```pytb
TypeError: WOT got an unexpected keyword argument 'use_rep'.
```

My `scdata` object (Single cell experiment stored as h5ad and imported to python) looks the following:
```pytb
AnnData object with n_obs × n_vars = 7464 × 20057
    obs: ...
    var: 'ENSEMBL', 'SYMBOL', 'HVG_general', 'HVG_T+NK', 'HVG_CD8'
    uns: 'X_name'
    obsm: 'PCA', 'UMAP'
    layers: 'X', 'counts'
```

I removed `obs` to shorten the output.

**Comment by michalk8** [comment]
Hi @schmeing , this is warning stems from how we set the transitions within the last time point - we use the `ConnectivityKernel` in that case, which needs the neighborhood graph.
Usually, this is constructed in the PCA space using `scanpy` (should be stored in `adata.obsm['X_pca']` by default).
To pass arguments to `scanpy.pp.neighbors`, you need to use `conn_kwargs` as e.g.
```python
wk.compute_transition_matrix(
    growth_iters=3,
    growth_rate_key="growth_rate_init",
    last_time_point="connectivities",
    use_highly_variable ="HVG_CD8",
    conn_kwargs={'use_rep': ...}
)
```
So you can either:
- use the defaults (with the above warning, there's no way to control it as of now) which will construct the PCA
  only based on cells within the last time point
- use `'X'` or other precomputed representation (such as the already defined "global" `PCA`)

I wouldn't recommend using `'use_rep': 'X'`, since it's too high-dimensional; either `'use_rep': 'PCA'` (global) or the default (local) should be fine.

**Comment by schmeing** [comment]
Thank you very much for the fast response. It works now!
