### ISSUE TITLE
Add kernel reading/writing to an example

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#904]
...
This could be part of the [kernel tricks](https://cellrank.readthedocs.io/en/stable/auto_examples/kernels/compute_kernel_tricks.html#sphx-glr-auto-examples-kernels-compute-kernel-tricks-py) example.

**Comment by dburkhardt** [comment]
Hi, I want to +1 for this. Due to some changes between pandas `1.5.3` and `2.0.0`, a kernel file written to disk as a pickle using pandas 1.5.3 cannot be read if you upgrade to pandas `>=2.0.0`.

The error looks like:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[9], line 4
      1 cyto_kernel_path = "/home/jovyan/data/cellrank/kernels/CytoTRACE.kernel.pickle"
      3 with open(cyto_kernel_path, "rb") as f:
----> 4     ctk = pickle.load(f)

ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'
```

It seems like the reverse works fine (i.e. they're backwards but not forwards compatible).

It seems like a better option, however, is the `write_to_anndata()`, which would be more compatible across versions. That said, I  don't see any documentation about how to use that beyond the function docstrings.

Let me know if I can help!

**Comment by dburkhardt** [comment]
Also, maybe this is just me, but I find it very frustrating when packages try to be smart about how they name files for me. If I pass `filename="my_file_name.pickle"`, I don't want it to add extensions by default. Can we set `ext=None` by default?
