### ISSUE TITLE
Initial state and one of the terminal states locate in the same cell cluster

### ISSUE THREAD

**Issue by BW15061999** [theislab/cellrank#931]
Hi,

When I try to run a dataset with day 4.5 and day 7 cells, cellrank  identifies one Initial state in day 4.5 and two terminal states.  And the Initial state and one of the terminal state are in the same cell cluster, with about half of the cells (16/30)  are the same in them.
I am not sure if it is the correct result for my analysis.

Thank you!

Best

**Comment by Marius1311** [comment]
Hello! It looks like you already know that this is *not* the correct result for your data 😎 I would recommend you to use the low-level interface where you interact directly with the GPCCA estimator. That allows you to set terminal states semi-manuallly using any prior knowledge you may have about your data set. Feel free to check the corresponding tutorials.

**Comment by BW15061999** [comment]
Thank you! I will have a try on that. 
But another problem is that I am not quite sure if 7d cells are the terminal states, becaues most of them are memory cells that could differentiate back to 4.5d cells. And the some of the directions inferred from scvelo are from 7d to 4.5d. Although I have asked the scvelo team if scvelo could be run on cells with 3 days interval and checked a few related issues about **direction reversed from biological direction**, I am still not sure if the directions are correct, from 7d to 4.5d, or I didn't properly run the workflow.
Although it seems not like a cellrank issue, it would be great if you could give some suggestions

Best!
![image](https://user-images.githubusercontent.com/52130151/181573619-64ebe658-f3db-449f-a1ff-fe18bcb32bd1.png)

**Comment by Marius1311** [comment]
Hi there! sorry for the slow response. If you have time-series data, I guess it's biologically not possible to go backward, from day 7 to day 4.5. Thus, I would impose the directionality using our RealTimeKernel (rather than the velocity kernel, given that the results seem unreliable in your case), or, alternatively, if you know the root state, compute a pseudotime using any established algorithm, check that it makes sense, and feed it into CellRank's PseudoTimeKernel.
