### ISSUE TITLE
Approach to comparing conditions in paired samples 

### ISSUE THREAD

**Issue by asgerjakobsen** [theislab/cellrank#957]
...
Hi, thank you for developing this brilliant package. 

I was wondering if you could give me some advice on comparing conditions within a multisample experiment? I have data from hematopoietic cells from multiple samples, which were pre-processed together and integrated using Harmony to obtain a set of common embeddings. Within each sample, I have WT and mutant cells and I want to compare the cell fate probabilities between these conditions. 

1. I have computed pseudotime using the integrated Harmony embeddings, and this works well for my dataset. In your paper you combine velocity and connectivity kernels. Would there be any reason not to use pseudotime with velocity instead?

2. Given the uncertainites around batch correction for velocity computation, I have calculated velocities on an uncorrected knn graph, and then combine this with the pseudotime kernel. Is it reasonable to do this even though I know there substantial sample-to-sample differences? 

3. Would you suggest computing a kernel on the whole dataset, then use an estimator to compare conditions within each sample? Or would it be better to compute separate kernels for WT and mutant cells? I would like to be able to compare the fate probabilities of WT and mutant cells towards equivalent terminal and intermediate states.

4. It would be nice to plot an embedding streamline plot separately for WT and mutant cells, but it doesn't seem possible to do this on a subset of the transition matrix? Is there a way to do this?

Many thanks for your help!

**Comment by Marius1311** [comment]
Hi @asgerjakobsen, thanks for using CellRank and for these interesting questions. 
Re 1: No, it should be fine to combine the Velocity and PseudotimeKernels. Just make sure beforehand that RNA velocity works well on your data by checking e.g. high likelihood genes and whether their parameters fits converged. (see the scVelo package for advice and tutorials on this.)
Re 2: I would start with just a single sample to avoid being guided by batch effects. Once you're familiar with CellRank results on the single sample, I would try on the integrated object to see whether results generalize / which results might now generalize / which new results pop up, and whether they are batch-specific. In the worst case, you can perform an integrated analysis using just the PseudotimeKernel, this one has no batch-correction problem since you can use a corrected KNN graph (and that should be reasonable to obtain). 
Re 3: I would start by computing a kernel on the entire dataset and analyzing this jointly in one estimator. You can then check on the level of macrostates how they are composed of the different conditions, and you can compute joint fate probabilities which are then comparable across conditions. For example, such an analysis could reveal whether a certain terminal state is only reachable in a given condition. 
Re 4: I'm afraid this is not possible with our current implementation.

**Comment by asgerjakobsen** [comment]
Hi @Marius1311,
Thanks so much for your helpful reply.  I have another couple of questions:

1. It does look as though I will may to stick to a PseudotimeKernel. RNA velocity seems to work for some samples but not all. Would you expect any advantages to be gained from combining this with a ConnectivityKernel? Since pseudotime is built on KNN graph, I imagine not but thought it worth asking.

2. I am interested in comparing the dynamics of transitions from one state to another between conditions. I.e. The probability of a cell transitioning from an initial state to an intermediate state, and the probability of an intermediate cell transitioning to a terminal state. As I understand it, the absorption probabilities are really intended for terminal states (which sum to 1). What is the best way to look at intermediate states? Is the mean and the variance of time to absorption (mentioned in your tutorial) relevant to this?

Thanks, Asger

**Comment by Marius1311** [comment]
Hi @asgerjakobsen,
Re 1, no, I don't see any advantage from combining these
Re 2, this is a really good question - at the moment, we can't really assign probabilities to individual paths, but only to end states. You can of course include intermediate state as terminal states, however, that ignores the fact that some of the cell in intermediate states are moving on to terminal states. You could look at the coarse-grained transition matrix (can be visualized from the GPCCA estimator). However, fully solving this question is an open problem for us.

**Comment by asgerjakobsen** [comment]
Thanks @Marius1311 -  that makes sense. How would you use/interpret the mean time to absorption? Is this essentially the inverse of pseudotime?

**Comment by Marius1311** [comment]
That's a good question - I would say it's like the inverse of a trajectory-specific pseudotime because you can compute the time to absorption separately for each terminal state. You can also do it jointly for all states, in which case it would be sort of like an "inverse pseudotime". 

In any case, there are strong theoretical links with (conditional) mean first passage times, see e.g. http://www.tandfonline.com/doi/abs/10.1080/0020739950260510, https://www.tandfonline.com/doi/full/10.1080/17509653.2013.783187, http://arxiv.org/abs/1511.01067, https://linkinghub.elsevier.com/retrieve/pii/S0024379518301204 or also http://www.pnas.org/content/early/2018/02/16/1714723115 for a single-cell application (you need to search through the supplement to find it)

**Comment by ccasar** [comment]
Hi,

as a follow-up to this, assuming everything went well in the previous steps and there were no major batch effects between the samples, do you have some thoughts on how to test for differences between the absorption probabilities between different groups (if this is sensible at all)?

As an example, the plots below show the same data in a slightly different way, i.e. the absorption probabilities for cells from cluster 0 going towards the endpoints 2,5,7,8,10. Visually there seem to be slight differences, but I'm not sure what kind of testing framework would work well here. 
Since each cell has some probability value toward each endpoint, comparing the differences between blue and gold within endpoint 2 does not seem appropriate to me. 
![fate_box](https://user-images.githubusercontent.com/2711108/202448049-9a2d8683-2010-4992-9e74-b332d01ba295.png)

![fate_density](https://user-images.githubusercontent.com/2711108/202448054-1a893500-01a6-4103-b451-14aac84e9db2.png)

**Comment by Marius1311** [comment]
Hi @ccasar, that's a great question - I have never done this myself so my reply will be somewhat speculative; sorry about that. I think you're on the right track - this looks like a compositional testing question to me. Absorption probabilities per cell have to sum to one, thus, if you lower the probability for one terminal state, you automatically increase all the others. To avoid picking up these effects, you could check out compositional testing frameworks like scCODA (https://www.nature.com/articles/s41467-021-27150-6). It was originally designed for compositional shifts between cell type proportions in two conditions but maybe you can adapt it to the setting here? Seems to be a similar question to me. 

Documentation here: https://sccoda.readthedocs.io/en/latest/

**Comment by Marius1311** [comment]
I'm closing this as I assume the issue has been solved.
