### ISSUE TITLE
When compute_absorption_probabilities() - RuntimeError: Markov chain is irreducible.

### ISSUE THREAD

**Issue by spkhowe** [theislab/cellrank#967]
Hello, I'm trying to compute_absorption_probabilities() for my dataset and keep getting a RuntimeError.

```python

vk = VelocityKernel(test_adata)
vk.compute_transition_matrix()
g = GPCCA(vk)
g.compute_schur(n_components=20)
g.set_terminal_states(test_adata.obs['Terminal'])
g.compute_absorption_probabilities()
```

```pytb
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [98], line 1
----> 1 g.compute_absorption_probabilities()

File ~/.conda/envs/cellrank/lib/python3.9/site-packages/cellrank/tl/estimators/mixins/_absorption_probabilities.py:276, in AbsProbsMixin.compute_absorption_probabilities(self, keys, solver, use_petsc, time_to_absorption, n_jobs, backend, show_progress_bar, tol, preconditioner)
    274 rec_indices, trans_indices, lookup_dict = _get_cat_and_null_indices(term_states)
    275 if not len(trans_indices):
--> 276     raise RuntimeError("Markov chain is irreducible.")
    278 # create Q (restriction transient-transient), S (restriction transient-recurrent)
    279 q = self.transition_matrix[trans_indices, :][:, trans_indices]

RuntimeError: Markov chain is irreducible.

```

#### Versions:

> 
cellrank==1.5.1 scanpy==1.9.1 anndata==0.8.0 numpy==1.23.4 numba==0.56.3 scipy==1.9.3 pandas==1.5.0 pygpcca==1.0.4 scikit-learn==1.1.2 statsmodels==0.13.2 python-igraph==0.10.1 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.6.1 seaborn==0.12.0

**Comment by Marius1311** [comment]
Hi @spkhowe, this error appears when your single-cell graph is composed of several disconnected components, i.e you could have for example two groups of cells which are so extremely different that the KNN graph does not have a single connection between them. So this isn't a bug, CellRank is intended to behave this way because you cannot compute fate probabilities for such a case. Please inspect your KNN graph and run CellRank separately on the different components. 

You can read up about irreducibility of markov chains on Wikipedia: https://en.wikipedia.org/wiki/Markov_chain

@michalk8, do we still have the utility function that allows this to be investigated? i.e. computing communication classes? that's exactly what we would need in a case like this.

**Comment by michalk8** [comment]
Yes, it's [here](https://github.com/theislab/cellrank/blob/master/cellrank/_utils/_utils.py#L697).
